# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dwh-gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1108, 726)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1111, 781))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(20, 140, 1061, 441))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.buttonExtract = QtWidgets.QPushButton(self.tab)
        self.buttonExtract.setGeometry(QtCore.QRect(20, 610, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonExtract.setFont(font)
        self.buttonExtract.setObjectName("buttonExtract")
        self.buttonResetWH = QtWidgets.QPushButton(self.tab)
        self.buttonResetWH.setGeometry(QtCore.QRect(890, 610, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonResetWH.setFont(font)
        self.buttonResetWH.setObjectName("buttonResetWH")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(80, 80, 191, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(310, 80, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 80, 191, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(320, 10, 361, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.buttonRefresh = QtWidgets.QPushButton(self.tab)
        self.buttonRefresh.setGeometry(QtCore.QRect(230, 610, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRefresh.setFont(font)
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboPerpus = QtWidgets.QComboBox(self.tab_2)
        self.comboPerpus.setGeometry(QtCore.QRect(20, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboPerpus.setFont(font)
        self.comboPerpus.setObjectName("comboPerpus")
        self.comboPerpus.addItem("")
        self.comboPerpus.addItem("")
        self.comboTahun = QtWidgets.QComboBox(self.tab_2)
        self.comboTahun.setGeometry(QtCore.QRect(20, 210, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboTahun.setFont(font)
        self.comboTahun.setObjectName("comboTahun")
        self.comboTahun.addItem("")
        self.comboTahun.addItem("")
        self.comboTahun.addItem("")
        self.buttonLoad = QtWidgets.QPushButton(self.tab_2)
        self.buttonLoad.setGeometry(QtCore.QRect(20, 610, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonLoad.setFont(font)
        self.buttonLoad.setObjectName("buttonLoad")
        self.buttonReset = QtWidgets.QPushButton(self.tab_2)
        self.buttonReset.setGeometry(QtCore.QRect(20, 540, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset.setFont(font)
        self.buttonReset.setObjectName("buttonReset")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(460, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(250, 70, 831, 581))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(0, 0, 831, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setRowCount(5)
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setItem(0, 0, item)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_3.setGeometry(QtCore.QRect(0, 0, 831, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setRowCount(5)
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setObjectName("tableWidget_3")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setItem(0, 0, item)
        self.tabWidget_2.addTab(self.tab_4, "")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget_2.raise_()
        self.comboPerpus.raise_()
        self.comboTahun.raise_()
        self.buttonLoad.raise_()
        self.buttonReset.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        self.tabBulan = QtWidgets.QWidget()
        self.tabBulan.setObjectName("tabBulan")
        self.buttonReset_2 = QtWidgets.QPushButton(self.tabBulan)
        self.buttonReset_2.setGeometry(QtCore.QRect(20, 540, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset_2.setFont(font)
        self.buttonReset_2.setObjectName("buttonReset_2")
        self.comboBulan = QtWidgets.QComboBox(self.tabBulan)
        self.comboBulan.setGeometry(QtCore.QRect(20, 300, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBulan.setFont(font)
        self.comboBulan.setObjectName("comboBulan")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboPerpus_2 = QtWidgets.QComboBox(self.tabBulan)
        self.comboPerpus_2.setGeometry(QtCore.QRect(20, 120, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboPerpus_2.setFont(font)
        self.comboPerpus_2.setObjectName("comboPerpus_2")
        self.comboPerpus_2.addItem("")
        self.comboPerpus_2.addItem("")
        self.comboTahun_2 = QtWidgets.QComboBox(self.tabBulan)
        self.comboTahun_2.setGeometry(QtCore.QRect(20, 210, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboTahun_2.setFont(font)
        self.comboTahun_2.setObjectName("comboTahun_2")
        self.comboTahun_2.addItem("")
        self.comboTahun_2.addItem("")
        self.comboTahun_2.addItem("")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tabBulan)
        self.tabWidget_3.setGeometry(QtCore.QRect(250, 70, 831, 581))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 831, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setRowCount(5)
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        self.tabWidget_3.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 831, 551))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setRowCount(5)
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setObjectName("tableWidget_5")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.buttonLoad_2 = QtWidgets.QPushButton(self.tabBulan)
        self.buttonLoad_2.setGeometry(QtCore.QRect(20, 610, 211, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonLoad_2.setFont(font)
        self.buttonLoad_2.setObjectName("buttonLoad_2")
        self.label_5 = QtWidgets.QLabel(self.tabBulan)
        self.label_5.setGeometry(QtCore.QRect(490, 0, 221, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.tabBulan)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabBulan)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tabBulan)
        self.label_10.setGeometry(QtCore.QRect(20, 270, 211, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tabBulan, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1108, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonExtract.setText(_translate("MainWindow", "Extract Data"))
        self.buttonResetWH.setText(_translate("MainWindow", "Reset Warehouse"))
        self.label_2.setText(_translate("MainWindow", "FROM"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Perpustakaan"))
        self.label_3.setText(_translate("MainWindow", "TO"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Warehouse"))
        self.label_4.setText(_translate("MainWindow", "WAREHOUSE PERPUSTAKAAN"))
        self.buttonRefresh.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Database"))
        self.comboPerpus.setCurrentText(_translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus.setItemText(0, _translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus.setItemText(1, _translate("MainWindow", "Perpustakaan Jurusan"))
        self.comboTahun.setCurrentText(_translate("MainWindow", "2017"))
        self.comboTahun.setItemText(0, _translate("MainWindow", "2017"))
        self.comboTahun.setItemText(1, _translate("MainWindow", "2018"))
        self.comboTahun.setItemText(2, _translate("MainWindow", "2019"))
        self.buttonLoad.setText(_translate("MainWindow", "Load Data"))
        self.buttonReset.setText(_translate("MainWindow", "Reset Data"))
        self.label.setText(_translate("MainWindow", "PEMINJAMAN"))
        __sortingEnabled = self.tableWidget_2.isSortingEnabled()
        self.tableWidget_2.setSortingEnabled(False)
        self.tableWidget_2.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Member"))
        __sortingEnabled = self.tableWidget_3.isSortingEnabled()
        self.tableWidget_3.setSortingEnabled(False)
        item = self.tableWidget_3.item(0, 0)
        item.setText(_translate("MainWindow", "test"))
        self.tableWidget_3.setSortingEnabled(__sortingEnabled)
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Buku"))
        self.label_6.setText(_translate("MainWindow", "Pilih Perpustakaan"))
        self.label_7.setText(_translate("MainWindow", "Pilih Tahun"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Data Warehouse"))
        self.buttonReset_2.setText(_translate("MainWindow", "Reset Data"))
        self.comboBulan.setCurrentText(_translate("MainWindow", "Januari"))
        self.comboBulan.setItemText(0, _translate("MainWindow", "Januari"))
        self.comboBulan.setItemText(1, _translate("MainWindow", "Februari"))
        self.comboBulan.setItemText(2, _translate("MainWindow", "Maret"))
        self.comboBulan.setItemText(3, _translate("MainWindow", "April"))
        self.comboBulan.setItemText(4, _translate("MainWindow", "Mei"))
        self.comboBulan.setItemText(5, _translate("MainWindow", "Juni"))
        self.comboBulan.setItemText(6, _translate("MainWindow", "Juli"))
        self.comboBulan.setItemText(7, _translate("MainWindow", "Agustus"))
        self.comboBulan.setItemText(8, _translate("MainWindow", "September"))
        self.comboBulan.setItemText(9, _translate("MainWindow", "Oktober"))
        self.comboBulan.setItemText(10, _translate("MainWindow", "November"))
        self.comboBulan.setItemText(11, _translate("MainWindow", "Desember"))
        self.comboPerpus_2.setCurrentText(_translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus_2.setItemText(0, _translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus_2.setItemText(1, _translate("MainWindow", "Perpustakaan Jurusan"))
        self.comboTahun_2.setCurrentText(_translate("MainWindow", "2017"))
        self.comboTahun_2.setItemText(0, _translate("MainWindow", "2017"))
        self.comboTahun_2.setItemText(1, _translate("MainWindow", "2018"))
        self.comboTahun_2.setItemText(2, _translate("MainWindow", "2019"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Member"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "test"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Buku"))
        self.buttonLoad_2.setText(_translate("MainWindow", "Load Data"))
        self.label_5.setText(_translate("MainWindow", "PEMINJAMAN"))
        self.label_8.setText(_translate("MainWindow", "Pilih Perpustakaan"))
        self.label_9.setText(_translate("MainWindow", "Pilih Tahun"))
        self.label_10.setText(_translate("MainWindow", "Pilih Bulan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBulan), _translate("MainWindow", "DWH Bulan"))

