# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_final.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1288, 907)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/iconbook/book2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1281, 881))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(20, 240, 1231, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.buttonExtract = QtWidgets.QPushButton(self.tab)
        self.buttonExtract.setGeometry(QtCore.QRect(20, 760, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonExtract.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/iconextract/add-to-database.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonExtract.setIcon(icon1)
        self.buttonExtract.setIconSize(QtCore.QSize(30, 30))
        self.buttonExtract.setCheckable(True)
        self.buttonExtract.setObjectName("buttonExtract")
        self.buttonResetWH = QtWidgets.QPushButton(self.tab)
        self.buttonResetWH.setGeometry(QtCore.QRect(1030, 760, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonResetWH.setFont(font)
        self.buttonResetWH.setAutoFillBackground(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/min/min-sql.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonResetWH.setIcon(icon2)
        self.buttonResetWH.setIconSize(QtCore.QSize(30, 30))
        self.buttonResetWH.setAutoDefault(False)
        self.buttonResetWH.setObjectName("buttonResetWH")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 51, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(90, 180, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setTabletTracking(False)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(310, 190, 31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(350, 180, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(470, 70, 471, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.buttonRefresh = QtWidgets.QPushButton(self.tab)
        self.buttonRefresh.setGeometry(QtCore.QRect(250, 760, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRefresh.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/refresh/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonRefresh.setIcon(icon3)
        self.buttonRefresh.setIconSize(QtCore.QSize(30, 30))
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(410, 60, 51, 71))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/iconbook/book2.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/setting/download (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab, icon4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboPerpus = QtWidgets.QComboBox(self.tab_2)
        self.comboPerpus.setGeometry(QtCore.QRect(40, 200, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboPerpus.setFont(font)
        self.comboPerpus.setObjectName("comboPerpus")
        self.comboPerpus.addItem("")
        self.comboPerpus.addItem("")
        self.comboTahun = QtWidgets.QComboBox(self.tab_2)
        self.comboTahun.setGeometry(QtCore.QRect(40, 290, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboTahun.setFont(font)
        self.comboTahun.setObjectName("comboTahun")
        self.comboTahun.addItem("")
        self.comboTahun.addItem("")
        self.comboTahun.addItem("")
        self.buttonLoad = QtWidgets.QPushButton(self.tab_2)
        self.buttonLoad.setGeometry(QtCore.QRect(40, 670, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonLoad.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/sql-query/sql_query.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonLoad.setIcon(icon5)
        self.buttonLoad.setIconSize(QtCore.QSize(30, 30))
        self.buttonLoad.setObjectName("buttonLoad")
        self.buttonReset = QtWidgets.QPushButton(self.tab_2)
        self.buttonReset.setGeometry(QtCore.QRect(40, 590, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset.setFont(font)
        self.buttonReset.setIcon(icon2)
        self.buttonReset.setIconSize(QtCore.QSize(30, 30))
        self.buttonReset.setObjectName("buttonReset")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(360, 30, 541, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(90, 170, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(90, 260, 111, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(50, 170, 21, 21))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/date/date.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(50, 260, 21, 21))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/date/date.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_4.setGeometry(QtCore.QRect(310, 130, 941, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_4.setFont(font)
        self.tabWidget_4.setAutoFillBackground(False)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tableWidget_6 = QtWidgets.QTableWidget(self.tab_7)
        self.tableWidget_6.setGeometry(QtCore.QRect(0, 0, 941, 661))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_6.setFont(font)
        self.tableWidget_6.setRowCount(5)
        self.tableWidget_6.setColumnCount(5)
        self.tableWidget_6.setObjectName("tableWidget_6")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setItem(0, 0, item)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/person/grab-vector-graphic-person-icon--imagebasket-13.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_4.addTab(self.tab_7, icon6, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_8)
        self.tableWidget_7.setGeometry(QtCore.QRect(0, 0, 941, 661))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_7.setFont(font)
        self.tableWidget_7.setRowCount(5)
        self.tableWidget_7.setColumnCount(5)
        self.tableWidget_7.setObjectName("tableWidget_7")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setItem(0, 0, item)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/book2/book3.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget_4.addTab(self.tab_8, icon7, "")
        self.buttonExcel_1 = QtWidgets.QPushButton(self.tab_2)
        self.buttonExcel_1.setGeometry(QtCore.QRect(40, 750, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonExcel_1.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/excel/icon-excel"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.buttonExcel_1.setIcon(icon8)
        self.buttonExcel_1.setIconSize(QtCore.QSize(30, 30))
        self.buttonExcel_1.setObjectName("buttonExcel_1")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/show/images (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon9, "")
        self.tabBulan = QtWidgets.QWidget()
        self.tabBulan.setObjectName("tabBulan")
        self.buttonReset_2 = QtWidgets.QPushButton(self.tabBulan)
        self.buttonReset_2.setGeometry(QtCore.QRect(40, 590, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonReset_2.setFont(font)
        self.buttonReset_2.setIcon(icon2)
        self.buttonReset_2.setIconSize(QtCore.QSize(30, 30))
        self.buttonReset_2.setObjectName("buttonReset_2")
        self.comboBulan = QtWidgets.QComboBox(self.tabBulan)
        self.comboBulan.setGeometry(QtCore.QRect(40, 380, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBulan.setFont(font)
        self.comboBulan.setObjectName("comboBulan")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboBulan.addItem("")
        self.comboPerpus_2 = QtWidgets.QComboBox(self.tabBulan)
        self.comboPerpus_2.setGeometry(QtCore.QRect(40, 200, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboPerpus_2.setFont(font)
        self.comboPerpus_2.setObjectName("comboPerpus_2")
        self.comboPerpus_2.addItem("")
        self.comboPerpus_2.addItem("")
        self.comboTahun_2 = QtWidgets.QComboBox(self.tabBulan)
        self.comboTahun_2.setGeometry(QtCore.QRect(40, 290, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboTahun_2.setFont(font)
        self.comboTahun_2.setObjectName("comboTahun_2")
        self.comboTahun_2.addItem("")
        self.comboTahun_2.addItem("")
        self.comboTahun_2.addItem("")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tabBulan)
        self.tabWidget_3.setGeometry(QtCore.QRect(310, 130, 941, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setAutoFillBackground(False)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 0, 941, 661))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setRowCount(5)
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setObjectName("tableWidget_4")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setItem(0, 0, item)
        self.tabWidget_3.addTab(self.tab_5, icon6, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_5 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_5.setGeometry(QtCore.QRect(0, 0, 1121, 591))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_5.setFont(font)
        self.tableWidget_5.setRowCount(5)
        self.tableWidget_5.setColumnCount(5)
        self.tableWidget_5.setObjectName("tableWidget_5")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setItem(0, 0, item)
        self.tabWidget_3.addTab(self.tab_6, icon7, "")
        self.buttonLoad_2 = QtWidgets.QPushButton(self.tabBulan)
        self.buttonLoad_2.setGeometry(QtCore.QRect(40, 670, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonLoad_2.setFont(font)
        self.buttonLoad_2.setIcon(icon5)
        self.buttonLoad_2.setIconSize(QtCore.QSize(30, 30))
        self.buttonLoad_2.setObjectName("buttonLoad_2")
        self.label_8 = QtWidgets.QLabel(self.tabBulan)
        self.label_8.setGeometry(QtCore.QRect(90, 170, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabBulan)
        self.label_9.setGeometry(QtCore.QRect(90, 260, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tabBulan)
        self.label_10.setGeometry(QtCore.QRect(90, 350, 141, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabBulan)
        self.label_11.setGeometry(QtCore.QRect(360, 30, 521, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tabBulan)
        self.label_12.setGeometry(QtCore.QRect(50, 170, 21, 21))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/date/date.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tabBulan)
        self.label_13.setGeometry(QtCore.QRect(50, 260, 21, 21))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/date/date.png"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tabBulan)
        self.label_14.setGeometry(QtCore.QRect(50, 350, 21, 21))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/date/date.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.buttonExcel_2 = QtWidgets.QPushButton(self.tabBulan)
        self.buttonExcel_2.setGeometry(QtCore.QRect(40, 750, 211, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonExcel_2.setFont(font)
        self.buttonExcel_2.setIcon(icon8)
        self.buttonExcel_2.setIconSize(QtCore.QSize(30, 30))
        self.buttonExcel_2.setObjectName("buttonExcel_2")
        self.tabWidget.addTab(self.tabBulan, icon9, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1288, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Warehouse | Kelompok 3"))
        self.buttonExtract.setText(_translate("MainWindow", "Extract Data"))
        self.buttonResetWH.setText(_translate("MainWindow", "Reset Warehouse"))
        self.label_2.setText(_translate("MainWindow", "FROM"))
        self.comboBox.setItemText(0, _translate("MainWindow", " Perpustakaan"))
        self.label_3.setText(_translate("MainWindow", "TO"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", " Warehouse"))
        self.label_4.setText(_translate("MainWindow", "WAREHOUSE PERPUSTAKAAN"))
        self.buttonRefresh.setText(_translate("MainWindow", " Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Database"))
        self.comboPerpus.setCurrentText(_translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus.setItemText(0, _translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus.setItemText(1, _translate("MainWindow", "Perpustakaan Jurusan"))
        self.comboTahun.setCurrentText(_translate("MainWindow", "2017"))
        self.comboTahun.setItemText(0, _translate("MainWindow", "2017"))
        self.comboTahun.setItemText(1, _translate("MainWindow", "2018"))
        self.comboTahun.setItemText(2, _translate("MainWindow", "2019"))
        self.buttonLoad.setText(_translate("MainWindow", "Load Data"))
        self.buttonReset.setText(_translate("MainWindow", "Reset Data"))
        self.label.setText(_translate("MainWindow", "WAREHOUSE PEMINJAMAN TAHUN"))
        self.label_6.setText(_translate("MainWindow", "Pilih Perpustakaan"))
        self.label_7.setText(_translate("MainWindow", "Pilih Tahun"))
        __sortingEnabled = self.tableWidget_6.isSortingEnabled()
        self.tableWidget_6.setSortingEnabled(False)
        self.tableWidget_6.setSortingEnabled(__sortingEnabled)
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_7), _translate("MainWindow", "Member"))
        __sortingEnabled = self.tableWidget_7.isSortingEnabled()
        self.tableWidget_7.setSortingEnabled(False)
        item = self.tableWidget_7.item(0, 0)
        item.setText(_translate("MainWindow", "test"))
        self.tableWidget_7.setSortingEnabled(__sortingEnabled)
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_8), _translate("MainWindow", "Buku"))
        self.buttonExcel_1.setText(_translate("MainWindow", "Export Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Warehouse Tahun"))
        self.buttonReset_2.setText(_translate("MainWindow", "Reset Data"))
        self.comboBulan.setCurrentText(_translate("MainWindow", "Januari"))
        self.comboBulan.setItemText(0, _translate("MainWindow", "Januari"))
        self.comboBulan.setItemText(1, _translate("MainWindow", "Februari"))
        self.comboBulan.setItemText(2, _translate("MainWindow", "Maret"))
        self.comboBulan.setItemText(3, _translate("MainWindow", "April"))
        self.comboBulan.setItemText(4, _translate("MainWindow", "Mei"))
        self.comboBulan.setItemText(5, _translate("MainWindow", "Juni"))
        self.comboBulan.setItemText(6, _translate("MainWindow", "Juli"))
        self.comboBulan.setItemText(7, _translate("MainWindow", "Agustus"))
        self.comboBulan.setItemText(8, _translate("MainWindow", "September"))
        self.comboBulan.setItemText(9, _translate("MainWindow", "Oktober"))
        self.comboBulan.setItemText(10, _translate("MainWindow", "November"))
        self.comboBulan.setItemText(11, _translate("MainWindow", "Desember"))
        self.comboPerpus_2.setCurrentText(_translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus_2.setItemText(0, _translate("MainWindow", "Perpustakaan Bersama"))
        self.comboPerpus_2.setItemText(1, _translate("MainWindow", "Perpustakaan Jurusan"))
        self.comboTahun_2.setCurrentText(_translate("MainWindow", "2017"))
        self.comboTahun_2.setItemText(0, _translate("MainWindow", "2017"))
        self.comboTahun_2.setItemText(1, _translate("MainWindow", "2018"))
        self.comboTahun_2.setItemText(2, _translate("MainWindow", "2019"))
        __sortingEnabled = self.tableWidget_4.isSortingEnabled()
        self.tableWidget_4.setSortingEnabled(False)
        self.tableWidget_4.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Member"))
        __sortingEnabled = self.tableWidget_5.isSortingEnabled()
        self.tableWidget_5.setSortingEnabled(False)
        item = self.tableWidget_5.item(0, 0)
        item.setText(_translate("MainWindow", "test"))
        self.tableWidget_5.setSortingEnabled(__sortingEnabled)
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Buku"))
        self.buttonLoad_2.setText(_translate("MainWindow", "Load Data"))
        self.label_8.setText(_translate("MainWindow", "Pilih Perpustakaan"))
        self.label_9.setText(_translate("MainWindow", "Pilih Tahun"))
        self.label_10.setText(_translate("MainWindow", "Pilih Bulan"))
        self.label_11.setText(_translate("MainWindow", "WAREHOUSE PEMINJAMAN BULAN"))
        self.buttonExcel_2.setText(_translate("MainWindow", "Export Excel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBulan), _translate("MainWindow", "Warehouse Bulan"))

import book_rc
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())